# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 731, 481))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.userNameList = QtGui.QListWidget(self.layoutWidget)
        self.userNameList.setObjectName(_fromUtf8("userNameList"))
        self.verticalLayout.addWidget(self.userNameList)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.userPasswordList = QtGui.QListWidget(self.layoutWidget)
        self.userPasswordList.setObjectName(_fromUtf8("userPasswordList"))
        self.verticalLayout_2.addWidget(self.userPasswordList)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.userRemarkList = QtGui.QListWidget(self.layoutWidget)
        self.userRemarkList.setObjectName(_fromUtf8("userRemarkList"))
        self.verticalLayout_3.addWidget(self.userRemarkList)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(560, 490, 160, 51))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.AddButton = QtGui.QPushButton(self.layoutWidget1)
        self.AddButton.setAutoFillBackground(False)
        self.AddButton.setAutoDefault(False)
        self.AddButton.setObjectName(_fromUtf8("AddButton"))
        self.horizontalLayout_2.addWidget(self.AddButton)
        self.DeleteButton = QtGui.QPushButton(self.layoutWidget1)
        self.DeleteButton.setObjectName(_fromUtf8("DeleteButton"))
        self.horizontalLayout_2.addWidget(self.DeleteButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDasd = QtGui.QMenu(self.menubar)
        self.menuDasd.setObjectName(_fromUtf8("menuDasd"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.save_nemu = QtGui.QAction(MainWindow)
        self.save_nemu.setObjectName(_fromUtf8("save_nemu"))
        self.load_nemu = QtGui.QAction(MainWindow)
        self.load_nemu.setObjectName(_fromUtf8("load_nemu"))
        self.new_folder_nemu = QtGui.QAction(MainWindow)
        self.new_folder_nemu.setObjectName(_fromUtf8("new_folder_nemu"))
        self.new_entry_nemu = QtGui.QAction(MainWindow)
        self.new_entry_nemu.setObjectName(_fromUtf8("new_entry_nemu"))
        self.undo_nemu = QtGui.QAction(MainWindow)
        self.undo_nemu.setObjectName(_fromUtf8("undo_nemu"))
        self.Redo_nemu = QtGui.QAction(MainWindow)
        self.Redo_nemu.setObjectName(_fromUtf8("Redo_nemu"))
        self.cut_nemu = QtGui.QAction(MainWindow)
        self.cut_nemu.setObjectName(_fromUtf8("cut_nemu"))
        self.copy_nemu = QtGui.QAction(MainWindow)
        self.copy_nemu.setObjectName(_fromUtf8("copy_nemu"))
        self.paste_nemu = QtGui.QAction(MainWindow)
        self.paste_nemu.setObjectName(_fromUtf8("paste_nemu"))
        self.rename_nemu = QtGui.QAction(MainWindow)
        self.rename_nemu.setObjectName(_fromUtf8("rename_nemu"))
        self.delete_nemu = QtGui.QAction(MainWindow)
        self.delete_nemu.setObjectName(_fromUtf8("delete_nemu"))
        self.find_nemu = QtGui.QAction(MainWindow)
        self.find_nemu.setObjectName(_fromUtf8("find_nemu"))
        self.find_next_nemu = QtGui.QAction(MainWindow)
        self.find_next_nemu.setObjectName(_fromUtf8("find_next_nemu"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionNewfile = QtGui.QAction(MainWindow)
        self.actionNewfile.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/yanghuan/.designer/backup/Icon/floder1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewfile.setIcon(icon)
        self.actionNewfile.setObjectName(_fromUtf8("actionNewfile"))
        self.actionSavefile = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/yanghuan/.designer/backup/Icon/f13.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSavefile.setIcon(icon1)
        self.actionSavefile.setObjectName(_fromUtf8("actionSavefile"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.menuDasd.addAction(self.new_entry_nemu)
        self.menuDasd.addSeparator()
        self.menuDasd.addAction(self.save_nemu)
        self.menuDasd.addAction(self.actionDelete)
        self.menuDasd.addSeparator()
        self.menuDasd.addAction(self.actionExit)
        self.menubar.addAction(self.menuDasd.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "用户名", None))
        self.label_2.setText(_translate("MainWindow", "密码", None))
        self.label_3.setText(_translate("MainWindow", "备注", None))
        self.AddButton.setText(_translate("MainWindow", "添加", None))
        self.DeleteButton.setText(_translate("MainWindow", "删除", None))
        self.menuDasd.setTitle(_translate("MainWindow", "File", None))
        self.save_nemu.setText(_translate("MainWindow", "Save", None))
        self.save_nemu.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.load_nemu.setText(_translate("MainWindow", "Load", None))
        self.load_nemu.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.new_folder_nemu.setText(_translate("MainWindow", "New folder", None))
        self.new_folder_nemu.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.new_entry_nemu.setText(_translate("MainWindow", "New entry", None))
        self.new_entry_nemu.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.undo_nemu.setText(_translate("MainWindow", "Undo", None))
        self.undo_nemu.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.Redo_nemu.setText(_translate("MainWindow", "Redo", None))
        self.Redo_nemu.setShortcut(_translate("MainWindow", "Ctrl+Y", None))
        self.cut_nemu.setText(_translate("MainWindow", "Cut", None))
        self.cut_nemu.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.copy_nemu.setText(_translate("MainWindow", "Copy", None))
        self.paste_nemu.setText(_translate("MainWindow", "Paste", None))
        self.paste_nemu.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.rename_nemu.setText(_translate("MainWindow", "Rename", None))
        self.rename_nemu.setShortcut(_translate("MainWindow", "F2", None))
        self.delete_nemu.setText(_translate("MainWindow", "Delete", None))
        self.find_nemu.setText(_translate("MainWindow", "Find", None))
        self.find_nemu.setShortcut(_translate("MainWindow", "F3", None))
        self.find_next_nemu.setText(_translate("MainWindow", "Find next", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionNewfile.setText(_translate("MainWindow", "newfile", None))
        self.actionNewfile.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionSavefile.setText(_translate("MainWindow", "savefile", None))
        self.actionSavefile.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionDelete.setText(_translate("MainWindow", "Delete", None))

